# SAC 2
behaviors:
  AgentBehaviour_1:
    trainer_type: sac
    hyperparameters:
      learning_rate: 0.0005
      learning_rate_schedule: linear
      batch_size: 512
      buffer_size: 5000000
      buffer_init_steps: 50000
      tau: 0.01
      steps_per_update: 5.0
      save_replay_buffer: false
      init_entcoef: 0.1
      reward_signal_steps_per_update: 5.0
    network_settings:
      normalize: true
      hidden_units: 512
      num_layers: 2
      vis_encode_type: simple
    reward_signals:
      extrinsic:
        gamma: 0.98
        strength: 1.0
    checkpoint_interval: 500000
    keep_checkpoints: 10
    max_steps: 150000000
    time_horizon: 512
    summary_freq: 100000
    threaded: true
