# PPO Hyperparameter Tuning
behaviors:
  AgentBehaviour_1:
    trainer_type: ppo
    hyperparameters:
      batch_size: 2048
      buffer_size: 204800
      learning_rate: 0.0005
      learning_rate_schedule: linear
      beta: 0.005
      epsilon: 0.15
      lambd: 0.90
      num_epoch: 5
    network_settings:
      normalize: true
      hidden_units: 512
      num_layers: 2
      vis_encode_type: simple
      memory:
        memory_size: 256
    reward_signals:
      extrinsic:
        gamma: 0.98
        strength: 1.0
    checkpoint_interval: 500000
    keep_checkpoints: 10
    max_steps: 150000000
    time_horizon: 512
    summary_freq: 100000
    threaded: true
