# SAC 3
behaviors:
  AgentBehaviour_1:
    trainer_type: sac
    hyperparameters:
      learning_rate: 0.0001
      learning_rate_schedule: constant
      batch_size: 1024
      buffer_size: 8000000
      buffer_init_steps: 200000
      tau: 0.002
      steps_per_update: 20.0
      save_replay_buffer: true
      init_entcoef: 0.05
      reward_signal_steps_per_update: 20.0
    network_settings:
      normalize: true
      hidden_units: 128
      num_layers: 4
      vis_encode_type: simple
    reward_signals:
      extrinsic:
        gamma: 0.995
        strength: 1.0
    checkpoint_interval: 500000
    keep_checkpoints: 10
    max_steps: 150000000
    time_horizon: 2048
    summary_freq: 100000
    threaded: true
