# PPO Hyperparameter Tuning
behaviors:
  AgentBehaviour_1:
    trainer_type: ppo
    hyperparameters:
      batch_size: 4096
      buffer_size: 409600
      learning_rate: 0.0003
      learning_rate_schedule: constant
      beta: 0.007
      epsilon: 0.2
      lambd: 0.95
      num_epoch: 3
    network_settings:
      normalize: true
      hidden_units: 256
      num_layers: 3
      vis_encode_type: simple
      memory:
        memory_size: 128
    reward_signals:
      extrinsic:
        gamma: 0.99
        strength: 1.0
    checkpoint_interval: 500000
    keep_checkpoints: 10
    max_steps: 300000000
    time_horizon: 1000
    summary_freq: 100000
    threaded: true

  AgentBehaviour_2:
    trainer_type: ppo
    hyperparameters:
      batch_size: 2048
      buffer_size: 204800
      learning_rate: 0.0005
      learning_rate_schedule: linear
      beta: 0.005
      epsilon: 0.15
      lambd: 0.90
      num_epoch: 5
    network_settings:
      normalize: true
      hidden_units: 512
      num_layers: 2
      vis_encode_type: simple
      memory:
        memory_size: 256
    reward_signals:
      extrinsic:
        gamma: 0.98
        strength: 1.0
    checkpoint_interval: 500000
    keep_checkpoints: 10
    max_steps: 300000000
    time_horizon: 512
    summary_freq: 100000
    threaded: true

  AgentBehaviour_3:
    trainer_type: ppo
    hyperparameters:
      batch_size: 8192
      buffer_size: 819200
      learning_rate: 0.0001
      learning_rate_schedule: constant
      beta: 0.01
      epsilon: 0.25
      lambd: 0.97
      num_epoch: 2
    network_settings:
      normalize: true
      hidden_units: 128
      num_layers: 4
      vis_encode_type: simple
      memory:
        memory_size: 64
    reward_signals:
      extrinsic:
        gamma: 0.995
        strength: 1.0
    checkpoint_interval: 500000
    keep_checkpoints: 10
    max_steps: 300000000
    time_horizon: 2048
    summary_freq: 100000
    threaded: true
