# PPO Hyperparameter Tuning
behaviors:
  AgentBehaviour_1:
    trainer_type: ppo
    hyperparameters:
      batch_size: 8192
      buffer_size: 819200
      learning_rate: 0.0001
      learning_rate_schedule: constant
      beta: 0.01
      epsilon: 0.25
      lambd: 0.97
      num_epoch: 2
    network_settings:
      normalize: true
      hidden_units: 128
      num_layers: 4
      vis_encode_type: simple
      memory:
        memory_size: 64
    reward_signals:
      extrinsic:
        gamma: 0.995
        strength: 1.0
    checkpoint_interval: 500000
    keep_checkpoints: 10
    max_steps: 150000000
    time_horizon: 2048
    summary_freq: 100000
    threaded: true
