# SAC Hyperparameter Tuning
behaviors:
  AgentBehaviour_1:
    trainer_type: sac
    hyperparameters:
      learning_rate: 0.0003
      learning_rate_schedule: constant
      batch_size: 256
      buffer_size: 4000000
      buffer_init_steps: 10000
      tau: 0.005
      steps_per_update: 10.0
      save_replay_buffer: true
      init_entcoef: 0.2
      reward_signal_steps_per_update: 10.0
    network_settings:
      normalize: true
      hidden_units: 256
      num_layers: 3
      vis_encode_type: simple
    reward_signals:
      extrinsic:
        gamma: 0.99
        strength: 1.0
    checkpoint_interval: 500000
    keep_checkpoints: 10
    max_steps: 300000000
    time_horizon: 1000
    summary_freq: 100000
    threaded: true

  AgentBehaviour_2:
    trainer_type: sac
    hyperparameters:
      learning_rate: 0.0005
      learning_rate_schedule: linear
      batch_size: 512
      buffer_size: 5000000
      buffer_init_steps: 50000
      tau: 0.01
      steps_per_update: 5.0
      save_replay_buffer: false
      init_entcoef: 0.1
      reward_signal_steps_per_update: 5.0
    network_settings:
      normalize: true
      hidden_units: 512
      num_layers: 2
      vis_encode_type: simple
    reward_signals:
      extrinsic:
        gamma: 0.98
        strength: 1.0
    checkpoint_interval: 500000
    keep_checkpoints: 10
    max_steps: 300000000
    time_horizon: 512
    summary_freq: 100000
    threaded: true

  AgentBehaviour_3:
    trainer_type: sac
    hyperparameters:
      learning_rate: 0.0001
      learning_rate_schedule: constant
      batch_size: 1024
      buffer_size: 8000000
      buffer_init_steps: 200000
      tau: 0.002
      steps_per_update: 20.0
      save_replay_buffer: true
      init_entcoef: 0.05
      reward_signal_steps_per_update: 20.0
    network_settings:
      normalize: true
      hidden_units: 128
      num_layers: 4
      vis_encode_type: simple
    reward_signals:
      extrinsic:
        gamma: 0.995
        strength: 1.0
    checkpoint_interval: 500000
    keep_checkpoints: 10
    max_steps: 300000000
    time_horizon: 2048
    summary_freq: 100000
    threaded: true
